import Link from "next/link";
import { ArrowUpRight, CheckCircle2, CircleAlert, Gauge, SearchCheck, ShieldCheck } from "lucide-react";

const priorities = [
  ["High impact", "Compress oversized homepage images", "Large images delay the first meaningful view on mobile.", "Convert hero and gallery assets to AVIF or WebP, then serve responsive sizes."],
  ["High impact", "Add alt text to product photography", "Important visual content is not described for assistive technology.", "Write concise alt text for each product image that adds meaning."],
  ["Quick win", "Improve mobile text contrast", "Some secondary text is difficult to read against its background.", "Increase contrast for muted copy to meet accessible contrast guidance."],
];

export default function ExamplePage() {
  return <main>
    <nav className="nav shell"><Link href="/" className="brand">launch<span>lens</span></Link><div className="nav-links"><Link href="/example">Example report</Link><Link href="/#how-it-works">How it works</Link></div></nav>
    <article className="example-report-page shell">
      <header className="example-masthead"><div><p className="kicker">Example website audit</p><h1>Brightfield Studio</h1><a href="https://brightfield.studio" className="example-url">brightfield.studio <ArrowUpRight size={14}/></a></div><p>Audited October 24, 2026<br /><span>Example report · Mobile-first analysis</span></p></header>
      <section className="example-overview"><div className="example-health-score"><p>Website health</p><strong>84</strong><span>out of 100</span></div><div className="example-health-copy"><p className="kicker">Strong foundation</p><h2>Your site is in good shape.<br />A few focused fixes will make it stronger.</h2><p>Brightfield has a fast, trustworthy baseline. The highest-value next steps are improving image delivery and tightening accessibility details.</p></div></section>
      <section className="example-metric-rail"><div><Gauge size={20}/><span>Performance</span><strong>91</strong></div><div><SearchCheck size={20}/><span>Search readiness</span><strong>88</strong></div><div><ShieldCheck size={20}/><span>Accessibility</span><strong>76</strong></div></section>
      <section className="example-priorities"><div className="example-section-heading"><p className="kicker">Where to start</p><h2>Three actions worth taking</h2><p>Start here for the clearest improvement to your visitors&apos; experience.</p></div><ol>{priorities.map(([impact, title, detail, action], index) => <li key={title}><span className="priority-number">0{index + 1}</span><div className="priority-content"><div><span className="impact-label">{impact}</span><h3>{title}</h3></div><p>{detail}</p><div className="priority-action"><CheckCircle2 size={16}/>{action}</div></div></li>)}</ol></section>
      <div className="example-evidence-grid"><section className="example-evidence"><p className="kicker">Core Web Vitals</p><h2>Fast where it matters.</h2><div className="vitals"><div><strong>1.8s</strong><span>LCP</span><small>Largest Contentful Paint</small></div><div><strong>88ms</strong><span>INP</span><small>Interaction to Next Paint</small></div><div><strong>0.03</strong><span>CLS</span><small>Layout Shift</small></div><div><strong>1.1s</strong><span>FCP</span><small>First Contentful Paint</small></div></div><p className="source-note">Measured as Lighthouse lab data on a simulated mobile connection.</p></section><section className="example-evidence technical"><p className="kicker">Technical snapshot</p><h2>Strong technical hygiene.</h2><dl><div><dt>HTTPS</dt><dd><CheckCircle2 size={15}/> Enabled</dd></div><div><dt>Page title</dt><dd>Present</dd></div><div><dt>Canonical URL</dt><dd>Present</dd></div><div><dt>robots.txt</dt><dd>Found</dd></div><div><dt>Sitemap</dt><dd>Found</dd></div></dl></section></div>
      <section className="example-mobile-check"><div><p className="kicker">Visual check</p><h2>A healthy mobile first impression.</h2><p>LaunchLens reviews the actual page your visitors see, so recommendations are grounded in a real experience—not a checklist.</p><div className="mobile-check-note"><CircleAlert size={17}/> Review your mobile hero image first</div></div><div className="example-phone"><div className="phone-notch"/><div className="phone-site"><span>BRIGHTFIELD</span><i/><b>Space to do your best work.</b><em>Explore studios →</em></div></div></section>
    </article>
    <footer className="footer shell"><Link href="/" className="brand">launch<span>lens</span></Link><span>Website health, made clear.</span><div><Link href="/legal/privacy">Privacy</Link><Link href="/legal/terms">Terms</Link></div></footer>
  </main>;
}
