import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, ExternalLink, Info, TriangleAlert } from "lucide-react";
import { getReport } from "@/lib/storage";
import type { Severity } from "@/lib/types";
import { ReportActions } from "@/components/share-button";

const tone: Record<Severity, string> = { critical: "critical", high: "high", medium: "medium", low: "low" };
function formatDate(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const report = await getReport(id); if (!report || new Date(report.expiresAt) < new Date()) notFound();
  const categories = Object.values(report.categories);
  return <main className="report-page"><nav className="nav shell"><Link href="/" className="brand">launch<span>lens</span></Link><Link className="back-link" href="/"><ArrowLeft size={16}/> Run another audit</Link></nav>
    <section className="report-hero"><div className="shell"><div className="report-overline"><span className={`source-dot ${report.source}`} /> {report.source === "pagespeed" ? "Live Google Lighthouse audit" : "Technical audit"}</div><h1>{report.hostname}</h1><a className="url-link" href={report.url} target="_blank" rel="noreferrer">{report.url}<ExternalLink size={14}/></a><p className="report-date">Audited {formatDate(report.createdAt)} · Available until {formatDate(report.expiresAt)}</p><div className="score-grid"><div className="overall"><div className="score-ring"><b>{report.overallScore}</b><span>/100</span></div><div><p>Overall website health</p><strong>{report.overallScore >= 80 ? "Strong foundation" : report.overallScore >= 60 ? "Needs attention" : "Action needed"}</strong></div></div>{categories.map(item => <div className="category" key={item.label}><b>{item.score}</b><span>{item.label}</span></div>)}</div></div></section>
    <section className="shell report-content"><ReportActions />
      <div className="section-heading"><p className="kicker">Where to start</p><h2>Your highest-impact actions</h2><p>These are the clearest opportunities we found. Fix the top items first.</p></div>
      <div className="findings">{report.findings.length ? report.findings.map(finding => <article className="finding" key={finding.id}><div className={`severity ${tone[finding.severity]}`}>{finding.severity === "critical" ? <TriangleAlert size={18}/> : <Info size={18}/>}<span>{finding.severity}</span></div><div><h3>{finding.title}</h3><p>{finding.detail}</p><div className="action"><CheckCircle2 size={16}/><span>{finding.action}</span></div></div></article>) : <article className="finding clean"><CheckCircle2 size={20}/><div><h3>Great work — no priority issues found.</h3><p>The baseline checks passed. Keep monitoring performance as your site changes.</p></div></article>}</div>
      <div className="details-grid"><section className="panel"><p className="kicker">Core Web Vitals</p><h2>Mobile experience</h2><div className="metrics">{[["LCP", report.metrics.lcp, "Largest Contentful Paint"],["INP", report.metrics.inp, "Interaction to Next Paint"],["CLS", report.metrics.cls, "Cumulative Layout Shift"],["FCP", report.metrics.fcp, "First Contentful Paint"]].map(([label, value, desc]) => <div key={label}><b>{value || "—"}</b><span>{label}</span><small>{desc}</small></div>)}</div><p className="muted">{report.source === "pagespeed" ? "Lab data from Google Lighthouse. Real-user field data is displayed when Google has enough samples." : "Add a Google PageSpeed API key to show measured lab metrics."}</p></section>
      <section className="panel"><p className="kicker">Technical snapshot</p><h2>What we detected</h2><dl className="snapshot"><div><dt>Page title</dt><dd>{report.metadata.title || "Missing"}</dd></div><div><dt>Meta description</dt><dd>{report.metadata.description || "Missing"}</dd></div><div><dt>HTTPS</dt><dd>{report.metadata.hasHttps ? "Enabled" : "Not detected"}</dd></div><div><dt>H1 headings</dt><dd>{report.metadata.h1Count}</dd></div><div><dt>robots.txt</dt><dd>{report.metadata.hasRobots ? "Found" : "Not found"}</dd></div><div><dt>sitemap.xml</dt><dd>{report.metadata.hasSitemap ? "Found" : "Not found"}</dd></div></dl></section></div>
      {report.screenshots.mobile && <section className="screenshot-section"><div className="section-heading"><p className="kicker">Visual check</p><h2>Your website on mobile</h2></div><div className="device"><img src={report.screenshots.mobile} alt={`Mobile screenshot of ${report.hostname}`} /></div></section>}
      <p className="report-disclaimer">LaunchLens provides automated technical guidance, not a guarantee of search rankings, accessibility compliance, or business results.</p>
    </section><footer className="footer shell"><Link href="/" className="brand">launch<span>lens</span></Link><span>Website health, made clear.</span><div><Link href="/legal/privacy">Privacy</Link><Link href="/legal/terms">Terms</Link></div></footer></main>;
}
