import { ArrowUpRight, CheckCircle2, Gauge, SearchCheck, ShieldCheck } from "lucide-react";
import type { AuditReport, Severity } from "@/lib/types";
import { ReportActions } from "@/components/share-button";

const labels = { performance: Gauge, seo: SearchCheck, accessibility: ShieldCheck, bestPractices: CheckCircle2 };
const metricHelp = { lcp: "Largest Contentful Paint", inp: "Interaction to Next Paint", cls: "Cumulative Layout Shift", fcp: "First Contentful Paint" };
const impact: Record<Severity, string> = { critical: "Critical", high: "High impact", medium: "Important", low: "Quick win" };
function formatDate(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
export function AuditReportView({ report, example = false }: { report: AuditReport; example?: boolean }) {
  return <article className="example-report-page shell">
    <header className="example-masthead"><div><p className="kicker">{example ? "Example website audit" : report.source === "pagespeed" ? "Live Google Lighthouse audit" : "Technical website audit"}</p><h1>{report.hostname}</h1><a href={report.url} target="_blank" rel="noreferrer" className="example-url">{report.url.replace(/^https?:\/\//, "")} <ArrowUpRight size={14}/></a></div><p>Audited {formatDate(report.createdAt)}<br /><span>{example ? "Example report · Mobile-first analysis" : `Available until ${formatDate(report.expiresAt)}`}</span></p></header>
    {!example && <div className="report-view-actions"><ReportActions /></div>}
    <section className="example-overview"><p className="kicker overview-kicker">Website health</p><div className="example-overview-body"><div className="example-health-score"><div className="score-value"><strong>{report.overallScore}</strong><span>/ out of 100</span></div></div><div className="example-health-copy"><h2>{report.overallScore >= 80 ? "Your site is in good shape.\nA few focused fixes will make it stronger." : "Your site has a clear path to improvement."}</h2><p>{report.findings.length ? "These are the highest-value actions based on the technical signals we found." : "The baseline checks passed. Keep monitoring performance as your site changes."}</p></div></div></section>
    <section className="example-metric-rail" aria-label="Audit category scores">{Object.entries(report.categories).map(([key, category]) => { const Icon = labels[key as keyof typeof labels]; return <div key={key}><Icon size={20}/><span>{category.label}</span><strong>{category.score}</strong></div>; })}</section>
    <section className="example-priorities"><div className="example-section-heading"><p className="kicker">Where to start</p><h2>{report.findings.length ? "Your highest-impact actions" : "No priority actions found"}</h2><p>{report.findings.length ? "Start here for the clearest improvement to your visitors’ experience." : "The automated baseline checks passed for this page."}</p></div>{report.findings.length > 0 && <ol>{report.findings.map((finding, index) => <li key={finding.id}><span className="priority-number">0{index + 1}</span><div className="priority-content"><div><span className="impact-label">{impact[finding.severity]}</span><h3>{finding.title}</h3></div><p>{finding.detail}</p><div className="priority-action"><CheckCircle2 size={16}/>{finding.action}</div></div></li>)}</ol>}</section>
    <div className="example-evidence-grid"><section className="example-evidence"><p className="kicker">Core Web Vitals</p><h2>Mobile experience.</h2><div className="vitals">{Object.entries(report.metrics).map(([key, value]) => <div key={key}><strong>{value || "—"}</strong><span>{key.toUpperCase()}</span><small>{metricHelp[key as keyof typeof metricHelp]}</small></div>)}</div><p className="source-note">{report.source === "pagespeed" ? "Lighthouse lab data on a simulated mobile connection." : "Add a Google PageSpeed API key to show measured lab metrics."}</p></section><section className="example-evidence technical"><p className="kicker">Technical snapshot</p><h2>What we detected.</h2><dl><div><dt>HTTPS</dt><dd>{report.metadata.hasHttps ? <><CheckCircle2 size={15}/> Enabled</> : "Not detected"}</dd></div><div><dt>Page title</dt><dd>{report.metadata.title ? "Present" : "Missing"}</dd></div><div><dt>Canonical URL</dt><dd>{report.metadata.hasCanonical ? "Present" : "Missing"}</dd></div><div><dt>robots.txt</dt><dd>{report.metadata.hasRobots ? "Found" : "Not found"}</dd></div><div><dt>Sitemap</dt><dd>{report.metadata.hasSitemap ? "Found" : "Not found"}</dd></div></dl></section></div>
    {report.screenshots.mobile && <section className="audit-screenshot"><div><p className="kicker">Visual check</p><h2>Your website on mobile.</h2><p>Captured during this audit by Google Lighthouse.</p></div><img src={report.screenshots.mobile} alt={`Mobile screenshot of ${report.hostname}`} /></section>}
  </article>;
}
